# Generated by Django 6.0.5 on 2026-07-09 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='ai_score',
            field=models.IntegerField(default=0, help_text='AI lead score 0-100'),
        ),
        migrations.AddField(
            model_name='lead',
            name='ai_score_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='ai_score_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
    ]
