# Generated by Django 6.0.5 on 2026-07-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_lead_ai_score_lead_ai_score_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='closing_probability',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lead',
            name='closing_probability_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='closing_probability_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='ai_summary_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
