# Generated by Django 6.0.5 on 2026-07-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_lead_closing_probability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='churn_risk',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='churn_risk_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='churn_risk_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='lifetime_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='lead',
            name='lifetime_value_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='lifetime_value_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
