# Generated by Django 6.0.5 on 2026-07-13 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_lead_churn_risk_lead_churn_risk_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard', models.CharField(default='full', max_length=10)),
                ('leads', models.CharField(default='none', max_length=10)),
                ('contacts', models.CharField(default='none', max_length=10)),
                ('pipeline', models.CharField(default='none', max_length=10)),
                ('quotations', models.CharField(default='none', max_length=10)),
                ('projects', models.CharField(default='none', max_length=10)),
                ('meetings', models.CharField(default='none', max_length=10)),
                ('tasks', models.CharField(default='none', max_length=10)),
                ('payments', models.CharField(default='none', max_length=10)),
                ('followups', models.CharField(default='none', max_length=10)),
                ('communications', models.CharField(default='none', max_length=10)),
                ('support', models.CharField(default='none', max_length=10)),
                ('activity', models.CharField(default='none', max_length=10)),
                ('reports', models.CharField(default='none', max_length=10)),
                ('documents', models.CharField(default='none', max_length=10)),
                ('contracts', models.CharField(default='none', max_length=10)),
                ('salespersons', models.CharField(default='none', max_length=10)),
                ('users', models.CharField(default='none', max_length=10)),
                ('ceo_dashboard', models.CharField(default='none', max_length=10)),
                ('whatsapp', models.CharField(default='none', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
