# Generated by Django 6.0.5 on 2026-07-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_userpermissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('re_scheduled', 'Re-Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20),
        ),
    ]
