# Generated by Django 6.0.5 on 2026-07-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0021_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='emails',
            field=models.CharField(default='none', max_length=10),
        ),
    ]
