# Generated by Django 6.0.6 on 2026-07-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0022_userpermissions_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='crm_chatbot',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='sales_chatbot',
            field=models.CharField(default='none', max_length=10),
        ),
    ]
