# Generated by Django 4.2.16 on 2026-07-23 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0024_alter_activitylog_id_alter_assistantauditlog_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calllog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='callschedule',
            options={'ordering': ['scheduled_time']},
        ),
        migrations.AddField(
            model_name='calllog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='googlecredential',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 7, 23, 8, 9, 7, 618387, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calllog',
            name='call_sid',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='channel',
            field=models.CharField(choices=[('phone', 'Phone (Twilio)'), ('whatsapp', 'WhatsApp (Meta Calling API)')], default='phone', max_length=20),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('ringing', 'Ringing'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('no-answer', 'No Answer'), ('rejected', 'Rejected')], default='initiated', max_length=20),
        ),
    ]
