# Generated by Django 5.2 on 2026-07-26 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0017_alter_activitylog_id_alter_communicationlog_id_and_more"),
        ("leads", "0025_alter_calllog_options_alter_callschedule_options_and_more"),
    ]

    operations = []
