# Generated by Django 4.2.16 on 2026-08-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0028_package_packageaccommodation_packageflight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='account_key',
            field=models.CharField(blank=True, default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='direction',
            field=models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound')], default='outbound', max_length=10),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='from_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_account_key',
            field=models.CharField(blank=True, default='default', max_length=50),
        ),
    ]
