# Generated by Django 6.1 on 2026-08-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0029_emaillog_account_key_emaillog_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='adults',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lead',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lead',
            name='destination',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='travel_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='travel_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='trip_type',
            field=models.CharField(blank=True, choices=[('package_tour', 'Package Tour'), ('group_tour', 'Group Tour'), ('private_tour', 'Private / Customized Tour'), ('honeymoon', 'Honeymoon Tour'), ('corporate', 'Corporate Travel'), ('umrah', 'Umrah'), ('hajj', 'Hajj'), ('visa_only', 'Visa Only'), ('air_ticket_only', 'Air Ticket Only'), ('hotel_only', 'Hotel Only'), ('transport_only', 'Transportation Only'), ('excursion', 'Excursion / Activity'), ('other', 'Other')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_source',
            field=models.CharField(choices=[('advertisement', 'Advertisement'), ('landline', 'Landline'), ('direct_call', 'Direct Call'), ('facebook', 'Facebook'), ('whatsapp', 'Whatsapp'), ('website', 'Website'), ('personal_reference', 'Personal Reference'), ('client_reference', 'Client Reference'), ('staff_reference', 'Staff Reference'), ('email', 'Email'), ('walkin', 'Walkin'), ('instagram', 'Instagram'), ('google', 'Google')], default='advertisement', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Super Admin'), ('agency_manager', 'Agency Manager'), ('sales_executive', 'Sales Agent'), ('visa_agent', 'Visa Agent'), ('operations', 'Operations Staff'), ('finance', 'Accountant'), ('marketing', 'Marketing User'), ('ceo', 'CEO')], default='sales_executive', max_length=30),
        ),
    ]
