# Generated by Django 6.1 on 2026-08-30 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0030_lead_adults_lead_budget_lead_children_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='item_type',
            field=models.CharField(choices=[('flight', 'Flight'), ('hotel', 'Hotel'), ('transport', 'Transport'), ('visa', 'Visa'), ('activity', 'Activity / Sightseeing'), ('insurance', 'Insurance'), ('service_charge', 'Service Charge'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='booking',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='packages',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='userpermissions',
            name='visa',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('approved', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='VisaApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=150)),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(max_length=100)),
                ('visa_category', models.CharField(choices=[('tourist', 'Tourist'), ('business', 'Business'), ('umrah', 'Umrah'), ('hajj', 'Hajj'), ('work', 'Work'), ('student', 'Student'), ('transit', 'Transit'), ('family_visit', 'Family Visit'), ('other', 'Other')], default='tourist', max_length=20)),
                ('application_type', models.CharField(blank=True, max_length=100, null=True)),
                ('embassy_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('processing_time_days', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('documents_required', 'Documents Required'), ('documents_received', 'Documents Received'), ('submitted', 'Submitted'), ('processing', 'Processing'), ('appointment', 'Appointment Scheduled'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('passport_returned', 'Passport Returned'), ('completed', 'Completed')], default='documents_required', max_length=25)),
                ('appointment_datetime', models.DateTimeField(blank=True, null=True)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('expected_decision_date', models.DateField(blank=True, null=True)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visa_applications', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visa_applications', to='leads.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisaDocumentChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('not_applicable', 'Not Applicable')], default='pending', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='visa_documents/%Y/%m/')),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='leads.visaapplication')),
            ],
        ),
    ]
