# Generated by Django 6.1.1 on 2026-09-16 06:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0032_hotel_supplier_remove_task_milestone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='bulk_email',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('positive', 'Positive'), ('quotation', 'Quotation Sent'), ('followup', 'Follow-up'), ('booking_pending', 'Booking Pending'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='BookingCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('flight_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('visa_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transport_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('food_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ziyarat_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('guide_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('insurance_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost', to='leads.booking')),
            ],
        ),
        migrations.CreateModel(
            name='PilgrimGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('name', models.CharField(help_text='e.g. KHAN FAMILY', max_length=150)),
                ('trip_type', models.CharField(choices=[('hajj', 'Hajj'), ('umrah', 'Umrah'), ('ziyarat', 'Ziyarat'), ('tour', 'Tour')], default='umrah', max_length=20)),
                ('season_year', models.PositiveIntegerField(default=2026)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pilgrim_groups', to='leads.booking')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pilgrim_groups', to='leads.lead')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pilgrim_groups', to='leads.package')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pilgrim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilgrim_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('father_husband_name', models.CharField(blank=True, max_length=150)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('nationality', models.CharField(default='Pakistani', max_length=80)),
                ('blood_group', models.CharField(blank=True, choices=[('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('ab+', 'AB+'), ('ab-', 'AB-'), ('o+', 'O+'), ('o-', 'O-')], max_length=5)),
                ('relationship', models.CharField(choices=[('leader', 'Group Leader'), ('husband', 'Husband'), ('wife', 'Wife'), ('son', 'Son'), ('daughter', 'Daughter'), ('father', 'Father'), ('mother', 'Mother'), ('brother', 'Brother'), ('sister', 'Sister'), ('relative', 'Other Relative'), ('friend', 'Friend'), ('other', 'Other')], default='leader', max_length=20)),
                ('cnic', models.CharField(blank=True, max_length=30)),
                ('passport_number', models.CharField(blank=True, max_length=40)),
                ('passport_expiry', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=30)),
                ('trip_type', models.CharField(choices=[('hajj', 'Hajj'), ('umrah', 'Umrah'), ('ziyarat', 'Ziyarat'), ('tour', 'Tour')], default='umrah', max_length=20)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('documents_pending', 'Documents Pending'), ('visa_processing', 'Visa Processing'), ('ready', 'Ready to Travel'), ('travelling', 'Travelling'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='registered', max_length=25)),
                ('visa_status', models.CharField(choices=[('documents_required', 'Documents Required'), ('documents_received', 'Documents Received'), ('submitted', 'Submitted'), ('processing', 'Processing'), ('appointment', 'Appointment Scheduled'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('passport_returned', 'Passport Returned'), ('completed', 'Completed')], default='documents_required', max_length=25)),
                ('room_number', models.CharField(blank=True, max_length=30)),
                ('flight_number', models.CharField(blank=True, max_length=30)),
                ('seat_number', models.CharField(blank=True, max_length=20)),
                ('travel_history', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pilgrims', to='leads.booking')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pilgrims', to='leads.lead')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pilgrims', to='leads.pilgrimgroup')),
            ],
            options={
                'ordering': ['group', 'relationship', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='PilgrimDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('cnic', 'CNIC'), ('photo', 'Passport Photo'), ('visa', 'Visa'), ('vaccination', 'Vaccination Certificate'), ('medical', 'Medical Certificate'), ('insurance', 'Travel Insurance'), ('ticket', 'Flight Ticket'), ('hotel_voucher', 'Hotel Voucher'), ('transport_voucher', 'Transport Voucher'), ('other', 'Other Document')], max_length=25)),
                ('status', models.CharField(choices=[('not_uploaded', 'Not Uploaded'), ('uploaded', 'Uploaded'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='not_uploaded', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='pilgrim_documents/%Y/%m/')),
                ('document_number', models.CharField(blank=True, max_length=60)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pilgrim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilgrim_documents', to='leads.pilgrim')),
            ],
            options={
                'ordering': ['pilgrim', 'document_type'],
                'unique_together': {('pilgrim', 'document_type')},
            },
        ),
    ]
