# Generated by Django 6.1.1 on 2026-09-18 04:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0033_userpermissions_bulk_email_alter_lead_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transportschedule',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_schedules', to='leads.pilgrimgroup'),
        ),
        migrations.AddField(
            model_name='transportschedule',
            name='pilgrims',
            field=models.ManyToManyField(blank=True, related_name='transport_assignments', to='leads.pilgrim'),
        ),
        migrations.CreateModel(
            name='BookingFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leg', models.CharField(choices=[('outbound', 'Outbound'), ('return', 'Return'), ('internal', 'Internal / Connecting')], default='outbound', max_length=10)),
                ('airline', models.CharField(blank=True, max_length=100)),
                ('flight_no', models.CharField(blank=True, max_length=30)),
                ('pnr', models.CharField(blank=True, max_length=50)),
                ('origin', models.CharField(blank=True, max_length=100)),
                ('destination', models.CharField(blank=True, max_length=100)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ticketed', 'Ticketed'), ('changed', 'Changed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='scheduled', max_length=15)),
                ('ticket_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_flights', to='leads.booking')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_flights', to='leads.pilgrimgroup')),
            ],
            options={
                'ordering': ['departure_date', 'departure_time'],
            },
        ),
        migrations.CreateModel(
            name='BookingInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Installment', max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='leads.booking')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='BookingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('payment', 'Payment Received'), ('refund', 'Refund Issued')], default='payment', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('card', 'Credit / Debit Card'), ('easypaisa', 'Easypaisa'), ('jazzcash', 'JazzCash'), ('cheque', 'Cheque'), ('other', 'Other')], default='bank_transfer', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Transaction / cheque / slip number', max_length=80)),
                ('receipt_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='leads.booking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_transactions', to=settings.AUTH_USER_MODEL)),
                ('installment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='leads.bookinginstallment')),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_notes', models.CharField(blank=True, max_length=255)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to='leads.booking')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_requests_made', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_request', to='leads.bookingtransaction')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ZiyaratActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Jabal-e-Noor, Masjid-e-Quba', max_length=150)),
                ('city', models.CharField(choices=[('makkah', 'Makkah'), ('madinah', 'Madinah'), ('jeddah', 'Jeddah'), ('taif', 'Taif'), ('other', 'Other')], default='makkah', max_length=15)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('guide_name', models.CharField(blank=True, max_length=150)),
                ('guide_phone', models.CharField(blank=True, max_length=30)),
                ('is_included', models.BooleanField(default=True, help_text='Included in package vs paid add-on')),
                ('price_per_person', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ziyarat_activities', to='leads.booking')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ziyarat_activities', to='leads.pilgrimgroup')),
                ('transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ziyarat_activities', to='leads.transportschedule')),
            ],
            options={
                'verbose_name_plural': 'Ziyarat Activities',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='BookingFlightPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(blank=True, max_length=20)),
                ('baggage', models.CharField(blank=True, max_length=50)),
                ('ticket_number', models.CharField(blank=True, max_length=50)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='leads.bookingflight')),
                ('pilgrim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_assignments', to='leads.pilgrim')),
            ],
            options={
                'unique_together': {('flight', 'pilgrim')},
            },
        ),
        migrations.CreateModel(
            name='ZiyaratParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='leads.ziyaratactivity')),
                ('pilgrim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ziyarat_participations', to='leads.pilgrim')),
            ],
            options={
                'unique_together': {('activity', 'pilgrim')},
            },
        ),
    ]
