# Generated by Django 6.1.1 on 2026-09-18 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0034_transportschedule_group_transportschedule_pilgrims_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingflight',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_flights', to='leads.booking'),
        ),
    ]
