"""
Django settings for leadcrm project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from decouple import config

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "change-this-local-development-key"
)

DEBUG = True

# ALLOWED_HOSTS = ['92.112.181.72', 'localhost', '127.0.0.1']

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    ".vercel.app",
    "travelagency-crm2-zd7v.vercel.app",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'leads',
    'chatbot',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'leads.middleware.RoleAccessMiddleware',
]

CSRF_TRUSTED_ORIGINS = [
    "https://travelagency-crm2-zd7v.vercel.app",
]

ROOT_URLCONF = 'leadcrm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'leads.context_processors.sidebar_counts'
            ],
        },
    },
]

WSGI_APPLICATION = 'leadcrm.wsgi.application'



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'mail.synergyintegratedsolutions.pk'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False
EMAIL_HOST_USER = 'bdo@synergyintegratedsolutions.pk'
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = 'bdo@synergyintegratedsolutions.pk'


# New (Bilal Enterprise)
# ---------- Bilal Enterprise mailbox ----------
BILAL_EMAIL_HOST = 'mail.bilalenterprise.com'          # <-- FIXED: ye SMTP host hai, email nahi
BILAL_EMAIL_PORT = 465
BILAL_EMAIL_USE_SSL = True
BILAL_EMAIL_HOST_USER = 'bdo@bilalenterprise.com'
BILAL_EMAIL_HOST_PASSWORD = os.getenv('BILAL_EMAIL_HOST_PASSWORD')   # <-- alag env var, Synergy wale se mix na ho
BILAL_IMAP_HOST = 'mail.bilalenterprise.com'
BILAL_IMAP_PORT = 993


# ---------- Multi-account map (per-user sending) ----------
EMAIL_ACCOUNTS = {
    'default': {
        'HOST': EMAIL_HOST,
        'PORT': EMAIL_PORT,
        'HOST_USER': EMAIL_HOST_USER,
        'HOST_PASSWORD': EMAIL_HOST_PASSWORD,
        'USE_SSL': True,
        'USE_TLS': False,
        'IMAP_HOST': os.getenv('IMAP_HOST', 'mail.synergyintegratedsolutions.pk'),
        'IMAP_PORT': int(os.getenv('IMAP_PORT', 993)),
    },
    'bilal_enterprise': {
        'HOST': BILAL_EMAIL_HOST,
        'PORT': BILAL_EMAIL_PORT,
        'HOST_USER': BILAL_EMAIL_HOST_USER,
        'HOST_PASSWORD': BILAL_EMAIL_HOST_PASSWORD,
        'USE_SSL': True,
        'USE_TLS': False,
        'IMAP_HOST': BILAL_IMAP_HOST,
        'IMAP_PORT': BILAL_IMAP_PORT,
    },
}

# Debug
EMAIL_TIMEOUT = 30

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "travelcrm_new",
        "USER": "postgres",
        "PASSWORD": os.getenv("DB_PASSWORD", ""),
        "HOST": "localhost",
        "PORT": "5432",
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Karachi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Meta WhatsApp Cloud API
META_WHATSAPP_TOKEN = os.getenv('META_WHATSAPP_TOKEN', '')
META_PHONE_NUMBER_ID = os.getenv('META_PHONE_NUMBER_ID', '')
META_VERIFY_TOKEN = os.getenv('META_VERIFY_TOKEN', 'leadcrm123')


TWILIO_ACCOUNT_SID = 'your_sid'
TWILIO_AUTH_TOKEN = 'your_auth_token'
TWILIO_PHONE_NUMBER = '+1XXXXXXXXXX'          # normal calling number
TWILIO_WHATSAPP_NUMBER = 'whatsapp:+1XXXXXXXXXX'  
GOOGLE_CLIENT_ID = 'your_client_id'
GOOGLE_CLIENT_SECRET = 'your_client_secret'
GOOGLE_REDIRECT_URI = 'http://127.0.0.1:8000/google/callback/'

# SITE_BASE_URL = 'http://127.0.0.1:8000'  

SITE_BASE_URL = os.getenv(
    "SITE_BASE_URL",
    "http://127.0.0.1:8000"
)


# ---------- Twilio (phone calling) ----------
TWILIO_ACCOUNT_SID = os.environ.get('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.environ.get('TWILIO_AUTH_TOKEN', '')
TWILIO_PHONE_NUMBER = os.environ.get('TWILIO_PHONE_NUMBER', '')  # e.g. +1XXXXXXXXXX
AGENT_FALLBACK_NUMBER = os.environ.get('AGENT_FALLBACK_NUMBER', '')  # default agent number if none passed

# ---------- Meta WhatsApp Calling API ----------
# Requires: WhatsApp Business Account, Cloud API access, phone number registered
# for calling in Meta Business Manager (Settings > WhatsApp Accounts > Phone numbers > Calling).
META_WA_PHONE_NUMBER_ID = os.environ.get('META_WA_PHONE_NUMBER_ID', '')
META_WA_ACCESS_TOKEN = os.environ.get('META_WA_ACCESS_TOKEN', '')  # system user permanent token
META_WA_API_VERSION = 'v20.0'  # bump as Meta releases newer versions
META_WA_VERIFY_TOKEN = os.environ.get('META_WA_VERIFY_TOKEN', 'change-this-verify-token')  # for webhook verification

# ---------- Google Calendar ----------
GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = os.environ.get('GOOGLE_CLIENT_SECRET', '')
GOOGLE_SCOPES = ['https://www.googleapis.com/auth/calendar']

# OpenAI AI

OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')

# ---------- Twilio (phone calling) ----------
TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN', '')
TWILIO_PHONE_NUMBER = os.getenv('TWILIO_PHONE_NUMBER', '')
AGENT_FALLBACK_NUMBER = os.getenv('AGENT_FALLBACK_NUMBER', '')

# ---------- Site base URL (used for Twilio/Meta webhooks + Google redirect) ----------
SITE_BASE_URL = os.getenv('SITE_BASE_URL', 'http://127.0.0.1:8000')

# ---------- Meta WhatsApp Calling API ----------
META_WA_PHONE_NUMBER_ID = os.getenv('META_WA_PHONE_NUMBER_ID', META_PHONE_NUMBER_ID)
META_WA_ACCESS_TOKEN = os.getenv('META_WA_ACCESS_TOKEN', META_WHATSAPP_TOKEN)
META_WA_API_VERSION = 'v20.0'
META_WA_VERIFY_TOKEN = os.getenv('META_WA_VERIFY_TOKEN', META_VERIFY_TOKEN)

# ---------- Google Calendar ----------
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = os.getenv('GOOGLE_CLIENT_SECRET', '')
GOOGLE_REDIRECT_URI = SITE_BASE_URL + '/google/callback/'
GOOGLE_SCOPES = ['https://www.googleapis.com/auth/calendar']

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')
